name: Set up dependencies
description: Set up dependencies for the project
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates libgettextpo-dev libgtest-dev

    - name: Install newer Clang
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install -y clang-tools-18

    - name: Install sarif-multitool
      shell: bash
      run: npm i -g @microsoft/sarif-multitool
