name: Lint C++ code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: none

jobs:
  lint:
    name: clang-format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: clang-format Check
        uses: jidicula/clang-format-action@37026c99e506c32f6dda1ae8cbf1e7df20506d9d # v4.12.0
        with:
          clang-format-version: 17
          check-path: src
